### ISSUE TITLE
Package @beyonk/snowpack-rollup-plugin not found

### ISSUE THREAD

**Issue by manuel3108** [beyonk-adventures/svelte-datepicker#10]
Just cloned the repo to submit some small changes, and wanted to run `npm i` and get the following error:
`'@beyonk/snowpack-rollup-plugin@https://registry.npmjs.org/@beyonk/snowpack-rollup-plugin/-/snowpack-rollup-plugin-0.0.1.tgz' is not in the npm registry.` 

Is this maybe also a package that you mistakenly made private? I was not able to find it in npm

**Comment by antony** [comment]
Ah yeah, I thought I'd made this public but clearly not.

There is a "semi official" snowpack plugin now, so perhaps we should change to that.

**Comment by manuel3108** [comment]
Works fine now. Thanks!
