### ISSUE TITLE
Selection over multiple month is broken when end property is set

### ISSUE THREAD

**Issue by manuel3108** [beyonk-adventures/svelte-datepicker#11]
Steps to reproduce: Set the end property of the Datepicker to today, and open the datepicker. The selection of the datepicker doesn't matches the expected output.

Current behaviour:
![image](https://user-images.githubusercontent.com/30698007/105837059-6a85fe00-5fce-11eb-92aa-28ff8f755f2c.png)

Expected behaviour: 
![image](https://user-images.githubusercontent.com/30698007/105837091-783b8380-5fce-11eb-8d09-c9365dd6ae45.png)

REPL:
https://svelte.dev/repl/51eb51b123b14d228013902629380bd3?version=3.31.2

**Comment by antony** [comment]
Ah yes - this is what I was referring to in your other issue. It looks like both sides are getting the same "selected" data.
