### ISSUE TITLE
Switching View between months is partially broken when end property is set

### ISSUE THREAD

**Issue by manuel3108** [beyonk-adventures/svelte-datepicker#12]
Steps to reproduce:
Set the end property of the Datepicker to today, and open the datepicker. Left view is in January 2020, right on in January 2021.
Now the problem is with the arrows to the left and right of each month name.
In the left view switching between Months works as expected (left is greyed out, as january is implicitly set by the datepicker to start of last year, right one works as expected)

The problem is with the right one.

Expected behaviour:
* The month back button on the right view is clickable and allows us to go back until February 2020. 
* The month forward button on the right view should be greyed out, because the end is today and we don't want to allow going to the next month.

Actual behaviour:
* The month back button on the right view is greyed out, and doesn't let us go back to February 2020. 
* The month forward button on the right view allows us to go to the next months.

REPL:
https://svelte.dev/repl/51eb51b123b14d228013902629380bd3?version=3.31.2

**Comment by antony** [comment]
Agreed. There's also another issue here, which is that the initial view shows 26th -> selected at the start, and then 26th -> selected on the January 2021 calendar, even though that is clearly incorrect.

**Comment by antony** [comment]
This was fixed by #16 :)
