### ISSUE TITLE
strange calendar placement

### ISSUE THREAD

**Issue by manuel3108** [beyonk-adventures/svelte-datepicker#24]
As of your comment in #21 , i just went ahead and tested it out.

I would say that its now better in our case,  but not good :)

Screenshot before clicking the Datepicker button:
![image](https://user-images.githubusercontent.com/30698007/107044167-3a0b4480-67c4-11eb-87b3-af5f11c1ed4d.png)

Screenshot after clicking the "Lieferdatum" (delivery date) button:
![image](https://user-images.githubusercontent.com/30698007/107044245-51e2c880-67c4-11eb-8a8d-743516733fc0.png)

It scrolls down way to much so that the button goes out of screenspace, which is not ideal.
Additionally the calendar is pulled to the right.

**Comment by manuel3108** [comment]
Just had a look at your code, and tried around a bit more:
https://github.com/beyonk-adventures/svelte-datepicker/commit/53047bd8340147b5cf600ba6695229eac7f26eb7

I think the 
```js
    setTimeout(() => {
      popover.recentre()
    }, 1)
```
should only occur, if the popover is not in the screen (partially).

But currently it also recenters, even if the displayed popover would be fully on the screen.

Also, as mentionend in my old PR, I think we should provide the ability to disable those two ifs with the hardcoded 480px. I think they are only causing problems.

**Comment by antony** [comment]
hey @manuel3108 

we have a strange side-case of wanting the calendar to work in an iframe too, which has its own series of conditions!

It definitely shouldn't pull right though, that is odd.

I'm happy for a PR to make the changes you suggest.

**Comment by antony** [comment]
Looks like we have some placement issues with the calendar anyway, so I'll be looking into fixing it.
