### ISSUE TITLE
Unable to disable auto scrolling when popup is opened

### ISSUE THREAD

**Issue by lucaspellegrinelli** [beyonk-adventures/svelte-datepicker#25]
In some websites the auto scrolling can create situations where the popup isn't where it should and anothers where the user experience may be compromised when everytime they change the date the website auto scrolls back.

I'd like to see another optional parameter to disable auto scrolling.

**Comment by antony** [comment]
@lucaspellegrinelli I'm not sure what auto scrolling has to do with the calendar though - can you go into more detail?

I don't think this component is responsible for any scrolling.

**Comment by lucaspellegrinelli** [comment]
> @lucaspellegrinelli I'm not sure what auto scrolling has to do with the calendar though - can you go into more detail?
> 
> I don't think this component is responsible for any scrolling.

Thanks for answering! I think this line does make it auto scroll when opened.
https://github.com/beyonk-adventures/svelte-datepicker/blob/ef2df7fff83a8264f820a0bbf5f7546ed2b3d6bd/src/components/Popover.svelte#L29

**Comment by antony** [comment]
I've removed this now, as part of the positioning work.

There are some small fixes to do, then we'll cut another major release.
