### ISSUE TITLE
We need a DEMO REPL ASAP.

### ISSUE THREAD

**Issue by frederikhors** [beyonk-adventures/svelte-datepicker#3]
We need a DEMO REPL ASAP.

**Comment by manuel3108** [comment]
Repl is not possible as this package is currently not published to npm.

But this code should work seamlessly (at least for me in sapper)
```svelte
<script>
	import DatePicker from "@beyonk/svelte-datepicker/src/components/DatePicker.svelte";
</script>

<DatePicker range={true}></DatePicker>
```

**Comment by antony** [comment]
Have I accidentally made it private? Oops! I see what the other issue is about now. I'll make it public.

**Comment by manuel3108** [comment]
Ah thanks. Here is a REPL: https://svelte.dev/repl/d812e880c6934f9e9a7cf9f760eddc11?version=3.31.2
