### ISSUE TITLE
SyntaxError with Svelte-Kit

### ISSUE THREAD

**Issue by gterras** [beyonk-adventures/svelte-datepicker#38]
Hi, 

Using datepicker with `@sveltejs/kit": "^1.0.0-next.111` I get a 

```
/node_modules/dayjs/esm/index.js:1
import * as C from './constant';
^^^^^^

SyntaxError: Cannot use import statement outside a module
``` 

with the following import (taken from official REPL) : 

```html
<script>
  import DatePicker from '@beyonk/svelte-datepicker/src/components/DatePicker.svelte'
</script>
<DatePicker range={true}></DatePicker>
```

Trying to `optimizeDeps` dayjs doesn't seem to do the trick. 

Thanks for your help

**Comment by antony** [comment]
I believe the dayjs library build works better as the cjs, not the esm, strangely!

Once I end up being able to migrate to Svelte Kit I'll be better positioned to support this. For now, I would suggest asking the wider community and we can work out a fix.
