### ISSUE TITLE
ETA for the official release of svelte-datepicker

### ISSUE THREAD

**Issue by mhatvan** [beyonk-adventures/svelte-datepicker#4]
I am running into issues with https://github.com/6eDesign/svelte-calendar and was hoping that this rewrite would fix that ;)

**Comment by manuel3108** [comment]
That would be really interesting to know.
I think this is the first easy to use range picker for svelte that looks like something

**Comment by antony** [comment]
We use this in prod :) so... Already!

Is there something specific you want in order to make it an official release?

**Comment by antony** [comment]
Ok, all public now. Sorry! https://www.npmjs.com/package/@beyonk/svelte-datepicker
