### ISSUE TITLE
Calendar is jumping a bit when switching between 4 and 5 week months

### ISSUE THREAD

**Issue by manuel3108** [beyonk-adventures/svelte-datepicker#6]
Minimum reproduction: https://svelte.dev/repl/d812e880c6934f9e9a7cf9f760eddc11?version=3.31.2
When switching between January 2021 and Dezember 2020 back and forward, you will see that the calendar is jumping up and down a bit.

Idea would be to increase the default size of the calendar a bit to top and bottom, so that a month with 5 weeks would easily fit in there and we would not have any jumping anymore.

**Comment by antony** [comment]
Do I remember you mentioning that you had fixed this? Do you have a PR for it?

**Comment by manuel3108** [comment]
Not currently, but I can create one :D

**Comment by antony** [comment]
Yeah if you have solved it, this actually never bothered me but now I know about it it does :laughing:
