### ISSUE TITLE
Cannot read properties of undefined (reading 'extend')

### ISSUE THREAD

**Issue by hitchhooker** [beyonk-adventures/svelte-datepicker#60]
```
Cannot read properties of undefined (reading 'extend')
TypeError: Cannot read properties of undefined (reading 'extend')
    at /node_modules/.pnpm/@beyonk+svelte-datepicker@12.0.1/node_modules/@beyonk/svelte-datepicker/src/components/lib/date-utils.js:7:7
    at async instantiateModule (/home/satoshi/code/interest/node_modules/.pnpm/vite@2.9.9/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:59333:9)

```

when using minimum example with svelte.config.js rules from repo.

documentation could include installation instructions, its often best thing to have. also adding code bars in examples would be great so wouldnt have to learn from source code

**Comment by Masatoshi** [comment]
try [dynamic importing](https://svelte.dev/repl/16b375da9b39417dae837b5006799cb4?version=3.25.0)

**Comment by gloverab** [comment]
Experiencing the same issue here. Were you able to get this working?

**Comment by Its-Just-Nans** [comment]
Hello,

Here is a possible solution : https://github.com/beyonk-adventures/svelte-datepicker/issues/61

@hitchhooker but you need to use vitejs ! (which use itself rollup)
